#!/usr/bin/env bash
# Install / upgrade tunnel-watchdog (idempotent).
#
#   curl -fsSL https://raw.githubusercontent.com/khodehamed/tunnel-watchdog/main/install.sh | sudo bash
#
set -euo pipefail

DEFAULT_RAW="https://raw.githubusercontent.com/khodehamed/tunnel-watchdog/main"
RAW_BASE="${TUNNEL_WATCHDOG_RAW:-$DEFAULT_RAW}"

LIB_DIR="/usr/local/lib/tunnel-watchdog"
BIN_DIR="/usr/local/bin"
CONF="/etc/tunnel-watchdog.conf"
UNIT_DIR="/etc/systemd/system"
FILES=(tunnel-lib.sh tunnel-menu tunnel-watchdog.sh tunnel-watchdog.service tunnel-watchdog.timer tunnel-watchdog.conf.example)

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Please run as root: curl -fsSL ... | sudo bash"
  exit 1
fi

for cmd in systemctl install ss journalctl curl; do
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "Missing required command: $cmd"
    exit 1
  }
done

SRC=""
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  _here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [[ -f "${_here}/tunnel-lib.sh" ]]; then
    SRC="$_here"
  fi
fi

TMP=""
if [[ -z "$SRC" ]]; then
  TMP="$(mktemp -d)"
  SRC="$TMP"
  echo "==> Downloading from $RAW_BASE"
  for f in "${FILES[@]}"; do
    curl -fsSL "${RAW_BASE%/}/$f" -o "${SRC}/$f"
  done
fi

chmod 755 "${SRC}/tunnel-menu" "${SRC}/tunnel-watchdog.sh" 2>/dev/null || true

echo "==> Installing / upgrading scripts"
mkdir -p "$LIB_DIR" "$BIN_DIR"
install -m 0644 "${SRC}/tunnel-lib.sh" "${LIB_DIR}/tunnel-lib.sh"
install -m 0755 "${SRC}/tunnel-menu" "${BIN_DIR}/tunnel-menu"
install -m 0755 "${SRC}/tunnel-watchdog.sh" "${BIN_DIR}/tunnel-watchdog.sh"
install -m 0644 "${SRC}/tunnel-watchdog.service" "${UNIT_DIR}/tunnel-watchdog.service"
install -m 0644 "${SRC}/tunnel-watchdog.timer" "${UNIT_DIR}/tunnel-watchdog.timer"

auto_detect_tunnels() {
  ls -1 /etc/systemd/system/*.service 2>/dev/null \
    | xargs -n1 basename \
    | grep -iE 'backhaul|backpack' \
    | grep -viE 'watchdog|webui' \
    | sort -u \
    | while read -r u; do
        [[ -z "$u" ]] && continue
        name="${u%.service}"
        conf="$(systemctl show "$u" -p ExecStart --value 2>/dev/null \
          | grep -oE '\-c[[:space:]]+[^[:space:]]+' | awk '{print $2}' || true)"
        port=""
        if [[ -n "$conf" && -f "$conf" ]]; then
          port="$(grep -E '^\s*remote_addr\s*=' "$conf" 2>/dev/null | head -1 | grep -oE '[0-9]+' | tail -1 || true)"
          if [[ -z "$port" ]]; then
            port="$(grep -E '^\s*bind_addr\s*=' "$conf" 2>/dev/null | head -1 | grep -oE '[0-9]+' | tail -1 || true)"
          fi
        fi
        if [[ -n "$port" ]]; then
          # dead_below=2 — only restart when almost no ESTAB sockets remain
          echo "${name}|${u}|control_channel|${port}:2"
        else
          echo "${name}|${u}|active|"
        fi
      done
}

# Soft-upgrade conf knobs without wiping TUNNELS
upgrade_conf_knobs() {
  local f="$1"
  local tmp
  tmp="$(mktemp)"
  awk '
    BEGIN { done_fail=0; done_cool=0; done_grace=0; done_j=0 }
    /^FAIL_THRESHOLD=/ { print "FAIL_THRESHOLD=5"; done_fail=1; next }
    /^COOLDOWN_SEC=/ { print "COOLDOWN_SEC=300"; done_cool=1; next }
    /^GRACE_SEC=/ { print "GRACE_SEC=300"; done_grace=1; next }
    /^CONTROL_JOURNAL_SINCE=/ { print "CONTROL_JOURNAL_SINCE=\"3 min ago\""; done_j=1; next }
    /^TUNNELS=/ {
      if (!done_fail) print "FAIL_THRESHOLD=5"
      if (!done_cool) print "COOLDOWN_SEC=300"
      if (!done_grace) print "GRACE_SEC=300"
      if (!done_j) print "CONTROL_JOURNAL_SINCE=\"3 min ago\""
      print
      next
    }
    { print }
    END {
      # if file had no TUNNELS somehow
    }
  ' "$f" >"$tmp"

  # Normalize old aggressive :3 mins to :2 in TUNNELS lines
  sed -E 's/\|control_channel\|([0-9]+):3$/|control_channel|\1:2/' "$tmp" >"${tmp}.2"
  # Drop webui lines if any
  grep -viE 'webui' "${tmp}.2" >"$tmp" || true
  install -m 0644 "$tmp" "$f"
  rm -f "$tmp" "${tmp}.2"
}

if [[ ! -f "$CONF" ]]; then
  echo "==> Creating $CONF"
  {
    echo "# Tunnel Watchdog — generated by install.sh on $(date -u '+%F %T') UTC"
    echo "# Manage with: tunnel-menu"
    echo "FAIL_THRESHOLD=5"
    echo "COOLDOWN_SEC=300"
    echo "GRACE_SEC=300"
    echo "JOURNAL_LOOKBACK=15min"
    echo 'CONTROL_JOURNAL_SINCE="3 min ago"'
    echo
    echo "TUNNELS=\""
    detected="$(auto_detect_tunnels || true)"
    if [[ -n "${detected:-}" ]]; then
      echo "$detected"
    else
      echo "# example|backhaul-xxx.service|control_channel|8080:2"
    fi
    echo '"'
  } >"$CONF"
  chmod 0644 "$CONF"
else
  echo "==> Upgrading safety knobs in existing $CONF (TUNNELS kept)"
  cp -a "$CONF" "${CONF}.bak.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
  upgrade_conf_knobs "$CONF"
fi

systemctl daemon-reload
systemctl enable --now tunnel-watchdog.timer >/dev/null
systemctl start tunnel-watchdog.service 2>/dev/null || true

[[ -n "$TMP" ]] && rm -rf "$TMP"

echo
echo "Done (safe defaults: FAIL_THRESHOLD=5, COOLDOWN=300s, GRACE=300s)."
echo "  tunnel-menu           # interactive menu"
echo "  tunnel-menu status    # live health"
echo "  config: $CONF"
echo
tunnel-menu status 2>/dev/null || true
