#!/usr/bin/env bash
# Install tunnel-watchdog (idempotent).
#
# One-liner (replace USER if needed):
#   curl -fsSL https://raw.githubusercontent.com/khodehamed/tunnel-watchdog/main/install.sh | sudo bash
#
set -euo pipefail

# Overridable: TUNNEL_WATCHDOG_RAW=https://raw.githubusercontent.com/khodehamed/tunnel-watchdog/main
DEFAULT_RAW="https://raw.githubusercontent.com/khodehamed/tunnel-watchdog/main"
RAW_BASE="${TUNNEL_WATCHDOG_RAW:-$DEFAULT_RAW}"

LIB_DIR="/usr/local/lib/tunnel-watchdog"
BIN_DIR="/usr/local/bin"
CONF="/etc/tunnel-watchdog.conf"
UNIT_DIR="/etc/systemd/system"
FILES=(tunnel-lib.sh tunnel-menu tunnel-watchdog.sh tunnel-watchdog.service tunnel-watchdog.timer tunnel-watchdog.conf.example)

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Please run as root: curl -fsSL ... | sudo bash"
  exit 1
fi

for cmd in systemctl install ss journalctl curl; do
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "Missing required command: $cmd"
    exit 1
  }
done

SRC=""
# Local checkout / extracted tree
if [[ -n "${BASH_SOURCE[0]:-}" && -f "${BASH_SOURCE[0]}" ]]; then
  _here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [[ -f "${_here}/tunnel-lib.sh" ]]; then
    SRC="$_here"
  fi
fi

TMP=""
if [[ -z "$SRC" ]]; then
  TMP="$(mktemp -d)"
  SRC="$TMP"
  echo "==> Downloading from $RAW_BASE"
  for f in "${FILES[@]}"; do
    curl -fsSL "${RAW_BASE%/}/$f" -o "${SRC}/$f"
  done
fi

chmod 755 "${SRC}/tunnel-menu" "${SRC}/tunnel-watchdog.sh" 2>/dev/null || true

echo "==> Installing files"
mkdir -p "$LIB_DIR" "$BIN_DIR"
install -m 0644 "${SRC}/tunnel-lib.sh" "${LIB_DIR}/tunnel-lib.sh"
install -m 0755 "${SRC}/tunnel-menu" "${BIN_DIR}/tunnel-menu"
install -m 0755 "${SRC}/tunnel-watchdog.sh" "${BIN_DIR}/tunnel-watchdog.sh"
install -m 0644 "${SRC}/tunnel-watchdog.service" "${UNIT_DIR}/tunnel-watchdog.service"
install -m 0644 "${SRC}/tunnel-watchdog.timer" "${UNIT_DIR}/tunnel-watchdog.timer"

auto_detect_tunnels() {
  local u name conf port
  ls -1 /etc/systemd/system/*.service 2>/dev/null \
    | xargs -n1 basename \
    | grep -iE 'backhaul|backpack' \
    | grep -viE 'watchdog|webui' \
    | sort -u \
    | while read -r u; do
        [[ -z "$u" ]] && continue
        name="${u%.service}"
        conf="$(systemctl show "$u" -p ExecStart --value 2>/dev/null \
          | grep -oE '\-c[[:space:]]+[^[:space:]]+' | awk '{print $2}' || true)"
        port=""
        if [[ -n "$conf" && -f "$conf" ]]; then
          port="$(grep -E '^\s*remote_addr\s*=' "$conf" 2>/dev/null | head -1 | grep -oE '[0-9]+' | tail -1 || true)"
          if [[ -z "$port" ]]; then
            port="$(grep -E '^\s*bind_addr\s*=' "$conf" 2>/dev/null | head -1 | grep -oE '[0-9]+' | tail -1 || true)"
          fi
        fi
        if [[ -n "$port" ]]; then
          echo "${name}|${u}|control_channel|${port}:3"
        else
          echo "${name}|${u}|active|"
        fi
      done
}

if [[ ! -f "$CONF" ]]; then
  echo "==> Creating $CONF"
  {
    echo "# Tunnel Watchdog — generated by install.sh on $(date -u '+%F %T') UTC"
    echo "# Manage with: tunnel-menu"
    echo "FAIL_THRESHOLD=3"
    echo "COOLDOWN_SEC=120"
    echo "JOURNAL_LOOKBACK=15min"
    echo 'CONTROL_JOURNAL_SINCE="5 min ago"'
    echo
    echo "TUNNELS=\""
    detected="$(auto_detect_tunnels || true)"
    if [[ -n "${detected:-}" ]]; then
      echo "$detected"
    else
      echo "# example|backhaul-xxx.service|control_channel|8080:3"
    fi
    echo '"'
  } >"$CONF"
  chmod 0644 "$CONF"
else
  echo "==> Keeping existing $CONF"
fi

systemctl daemon-reload
systemctl enable --now tunnel-watchdog.timer >/dev/null
systemctl start tunnel-watchdog.service 2>/dev/null || true

[[ -n "$TMP" ]] && rm -rf "$TMP"

echo
echo "Done."
echo "  tunnel-menu           # interactive menu"
echo "  tunnel-menu status    # live health"
echo "  config: $CONF"
echo
tunnel-menu status 2>/dev/null || true
